# Generated by Django 2.2.5 on 2019-09-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190928_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='checked_in',
            new_name='check_in',
        ),
    ]
